spring:
  application:
    name: SpringBootStudy-Redis
  profiles:
    active: dev
  http:
    encoding: UTF-8
  redis:
    lettuce:
      pool:
        max-wait: 3000 #最大阻塞等待时间，单位ms
        max-idle: 5 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
        max-active: 10 #最大连接数
        
server:
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /springBootStudy/redis



